baseURL = "https://LarissaCode-dev.github.io/"
languageCode = "en-us"
title = "LarissaCode Tech Tutorials"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true

enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
